name: Run Python and upload outputs

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: write   # ⬅ 커밋/푸시 위해 필요

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 커밋/푸시를 위해 전체 이력 필요할 수 있음

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pandas selenium webdriver-manager
          fi

      # 필요 시 환경 변수로 스크립트 이름 지정
      - name: Run script
        env:
          SCRIPT_NAME: balchun_9_wdm.py   # ← 여기만 바꾸면 됩니다
        run: |
          echo "Running $SCRIPT_NAME"
          python "$SCRIPT_NAME"

      - name: List files after script
        run: ls -al

      # 생성된 파일을 Artifacts로도 업로드
      - name: Upload artifacts (CSV/TXT)
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            *.csv
            *.txt
          if-no-files-found: warn

      # 레포지토리에 자동 커밋/푸시
      - name: Commit and push outputs to main
        if: ${{ github.event_name != 'pull_request' }}  # PR 이벤트에선 푸시 안 함
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # git 사용자 설정
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # 변경 파일만 스테이징 (없으면 스킵)
          git add *.csv *.txt 2>/dev/null || true

          # 커밋할 것이 있는지 확인
          if git diff --cached --quiet; then
            echo "No CSV/TXT changes to commit."
            exit 0
          fi

          git commit -m "Add generated outputs (CSV/TXT) from workflow run"
          # 리베이스/충돌 줄이기 위해 최신 반영 후 푸시
          git pull --rebase origin "${GITHUB_REF##*/}" || true
          git push origin "${GITHUB_REF##*/}"
