name: Run Python and upload outputs

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            # 최소한 자주 쓰는 패키지 예시 (없으면 제거 가능)
            python -m pip install pandas selenium webdriver-manager
          fi

      # 필요 시 환경 변수로 스크립트 이름 지정 가능
      - name: Run script
        env:
          SCRIPT_NAME: balchun_9.py   # ← 여기만 바꾸면 됩니다
        run: |
          echo "Running $SCRIPT_NAME"
          python "$SCRIPT_NAME"

      # 생성된 파일 업로드 (여기서 원하는 패턴을 추가/수정하세요)
      - name: Upload artifacts (CSV/TXT)
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            *.csv
            *.txt
          if-no-files-found: warn
          # retention-days: 30  # 보관 기간 조정 시 주석 해제

